language: node_js
node_js:
 - "8"
cache:
  directories:
    - node_modules
before_install:
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
  - npm i -g npm@4.2.0
install: npm i ytsearcher discordblacklist; npm i;
